local_library/catalog/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('books/', views.BookListView.as_view(), name='books'),
    path('book/<int:pk>', views.BookDetailView.as_view(), name='book-detail'),
    path('authors/', views.AuthorListView.as_view(), name='authors'),
    path('author/<int:pk>',
         views.AuthorDetailView.as_view(), name='author-detail'),
]


urlpatterns += [
    path('mybooks/', views.LoanedBooksByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedBooksAllListView.as_view(), name='all-borrowed'),  # Added for challenge
]


# Add URLConf for librarian to renew a book.
urlpatterns += [
    path('book/<uuid:pk>/renew/', views.renew_book_librarian, name='renew-book-librarian'),
]


# Add URLConf to create, update, and delete authors
urlpatterns += [
    path('author/create/', views.AuthorCreate.as_view(), name='author-create'),
    path('author/<int:pk>/update/', views.AuthorUpdate.as_view(), name='author-update'),
    path('author/<int:pk>/delete/', views.AuthorDelete.as_view(), name='author-delete'),
]

# Add URLConf to create, update, and delete books
urlpatterns += [
    path('book/create/', views.BookCreate.as_view(), name='book-create'),
    path('book/<int:pk>/update/', views.BookUpdate.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', views.BookDelete.as_view(), name='book-delete'),
]


# Add URLConf to list, view, create, update, and delete genre
urlpatterns += [
    path('genres/', views.GenreListView.as_view(), name='genres'),
    path('genre/<int:pk>', views.GenreDetailView.as_view(), name='genre-detail'),
    path('genre/create/', views.GenreCreate.as_view(), name='genre-create'),
    path('genre/<int:pk>/update/', views.GenreUpdate.as_view(), name='genre-update'),
    path('genre/<int:pk>/delete/', views.GenreDelete.as_view(), name='genre-delete'),
]

# Add URLConf to list, view, create, update, and delete languages
urlpatterns += [
    path('languages/', views.LanguageListView.as_view(), name='languages'),
    path('language/<int:pk>', views.LanguageDetailView.as_view(),
         name='language-detail'),
    path('language/create/', views.LanguageCreate.as_view(), name='language-create'),
    path('language/<int:pk>/update/',
         views.LanguageUpdate.as_view(), name='language-update'),
    path('language/<int:pk>/delete/',
         views.LanguageDelete.as_view(), name='language-delete'),
]

# Add URLConf to list, view, create, update, and delete bookinstances
urlpatterns += [
    path('bookinstances/', views.BookInstanceListView.as_view(), name='bookinstances'),
    path('bookinstance/<uuid:pk>', views.BookInstanceDetailView.as_view(),
         name='bookinstance-detail'),
    path('bookinstance/create/', views.BookInstanceCreate.as_view(),
         name='bookinstance-create'),
    path('bookinstance/<uuid:pk>/update/',
         views.BookInstanceUpdate.as_view(), name='bookinstance-update'),
    path('bookinstance/<uuid:pk>/delete/',
         views.BookInstanceDelete.as_view(), name='bookinstance-delete'),
]

local_library/locallibrary/urls.py
from django.contrib import admin
from django.urls import path

# Use include() to add URLS from the catalog application and authentication system
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
]


urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static


urlpatterns+= static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
]



#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

local_library/catalog/models.py
from django.db import models

# Create your models here.

from django.urls import reverse  # To generate URLS by reversing URL patterns


class Genre(models.Model):
    """Model representing a book genre (e.g. Science Fiction, Non Fiction)."""
    name = models.CharField(
        max_length=200,
        unique=True,
        help_text="Enter a book genre (e.g. Science Fiction, French Poetry etc.)"
    )

    def get_absolute_url(self):
        """Returns the url to access a particular genre instance."""
        return reverse('genre-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Language(models.Model):
    """Model representing a Language (e.g. English, French, Japanese, etc.)"""
    name = models.CharField(max_length=200,
                            unique=True,
                            help_text="Enter the book's natural language (e.g. English, French, Japanese etc.)")

    def get_absolute_url(self):
        """Returns the url to access a particular language instance."""
        return reverse('language-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object (in Admin site etc.)"""
        return self.name


class Book(models.Model):
    """Model representing a book (but not a specific copy of a book)."""
    title = models.CharField(max_length=200)
    author = models.ForeignKey('Author', on_delete=models.RESTRICT, null=True)
    # Foreign Key used because book can only have one author, but authors can have multiple books.
    # Author as a string rather than object because it hasn't been declared yet in file.
    summary = models.TextField(
        max_length=1000, help_text="Enter a brief description of the book")
    isbn = models.CharField('ISBN', max_length=13,
                            unique=True,
                            help_text='13 Character <a href="https://www.isbn-international.org/content/what-isbn'
                                      '">ISBN number</a>')
    genre = models.ManyToManyField(
        Genre, help_text="Select a genre for this book")
    # ManyToManyField used because a genre can contain many books and a Book can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    language = models.ForeignKey(
        'Language', on_delete=models.SET_NULL, null=True)

    class Meta:
        ordering = ['title', 'author']

    def display_genre(self):
        """Creates a string for the Genre. This is required to display genre in Admin."""
        return ', '.join([genre.name for genre in self.genre.all()[:3]])

    display_genre.short_description = 'Genre'

    def get_absolute_url(self):
        """Returns the url to access a particular book record."""
        return reverse('book-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return self.title


import uuid  # Required for unique book instances
from datetime import date

from django.conf import settings  # Required to assign User as a borrower


class BookInstance(models.Model):
    """Model representing a specific copy of a book (i.e. that can be borrowed from the library)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text="Unique ID for this particular book across whole library")
    book = models.ForeignKey('Book', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, blank=True)

    @property
    def is_overdue(self):
        """Determines if the book is overdue based on due date and current date."""
        return bool(self.due_back and date.today() > self.due_back)

    LOAN_STATUS = (
        ('d', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='d',
        help_text='Book availability')

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set book as returned"),)

    def get_absolute_url(self):
        """Returns the url to access a particular book instance."""
        return reverse('bookinstance-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.book.title})'


class Author(models.Model):
    """Model representing an author."""
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField('died', null=True, blank=True)

    class Meta:
        ordering = ['last_name', 'first_name']

    def get_absolute_url(self):
        """Returns the url to access a particular author instance."""
        return reverse('author-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.last_name}, {self.first_name}'

local_library/catalog/forms.py
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
import datetime  # for checking renewal date range.

from django import forms


class RenewBookForm(forms.Form):
    """Form for a librarian to renew books."""
    renewal_date = forms.DateField(
            help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check date is not in past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))
        # Check date is in range librarian allowed to change (+4 weeks)
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(
                _('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

local_library/catalog/templates/catalog/author_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Author: {{ author }} </h1>
<p>{{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %}</p>


<h4>Books</h4>

<dl>
{% for book in author.book_set.all %}
  <dt><a href="{% url 'book-detail' book.pk %}">{{book}}</a> ({{book.bookinstance_set.all.count}})</dt>
  <dd>{{book.summary}}</dd>
  {% empty %}
  <p>This author has no books.</p>
{% endfor %}
</dl>

</div>
{% endblock %}

{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_author or perms.catalog.delete_author %}
  <hr>
  <!-- <ul class="w3-sidebar w3-bar-block w3-light-grey" style="width:25%"> -->
  <div class="w3-sidebar w3-bar-block w3-light-grey" style="width:25%">
    {% if perms.catalog.change_author %}
      <!-- <li> -->
        <a href="{% url 'author-update' author.id %}"class="w3-bar-item w3-button w3-hover-blue">Update author</a>
      <!-- </li> -->
    {% endif %}
    {% if not author.book_set.all and perms.catalog.delete_author %}
      <!-- <li> -->
        <a href="{% url 'author-delete' author.id %}"class="w3-bar-item w3-button w3-hover-blue">Delete author</a>
      <!-- </li> -->
    {% endif %}
    <!-- </ul> -->
  {% endif %}
</div>
{% endblock %}

local_library/catalog/templates/catalog/author_list.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Author List</h1>

{% if author_list %}
  <ul>

  {% for author in author_list %}
    <li>
      <a href="{{ author.get_absolute_url }}">
      {{ author }} ({{author.date_of_birth}} - {% if author.date_of_death %}{{author.date_of_death}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no authors available.</p>
{% endif %}
        
        
</div>
{% endblock %}

local_library/catalog/templates/catalog/book_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Delete Book</h1>

{% if book.bookinstance_set.all %}
<p>You can't delete this book until all copies have been deleted:</p>

<ul>
{% for copy in book.bookinstance_set.all %}
  <li><a href="{{ copy.get_absolute_url }}">{{copy.id}}</a> (Imprint: {{copy.imprint}})</li>
{% endfor %}
</ul>

{% else %}
<p>Are you sure you want to delete the book: {{ book }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
{% endif %}
</div>
{% endblock %}

local_library/catalog/templates/catalog/book_form.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    
</form>
</div>
{% endblock %}

local_library/catalog/templates/catalog/book_list.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
    <h1>Book List</h1>

    {% if book_list %}
    <ul>

      {% for book in book_list %}
      <li>
        <a href="{{ book.get_absolute_url }}">{{ book.title }}</a> ({{book.author}})
      </li>
      {% endfor %}

    </ul>

    {% else %}
      <p>There are no books in the library.</p>
    {% endif %}  
  </div>
{% endblock %}

local_library/catalog/templates/catalog/book_renew_librarian.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
    <h1>Renew: {{book_instance.book.title}}</h1>
    <p>Borrower: {{book_instance.borrower}}</p>
    <p{% if book_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{book_instance.due_back}}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
    </form>
</div>
{% endblock %}

local_library/catalog/templates/catalog/bookinstance_form.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    
</form>
</div>
{% endblock %}

local_library/catalog/templates/catalog/bookinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
    <h1>All Borrowed Books</h1>

    {% if bookinstance_list %}
    <ul>

      {% for bookinst in bookinstance_list %} 
      <li class="{% if bookinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'book-detail' bookinst.book.pk %}">{{bookinst.book.title}}</a> ({{ bookinst.due_back }}) {% if user.is_staff %}- {{ bookinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-book-librarian' bookinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no books borrowed.</p>
    {% endif %}     
  </div>  
{% endblock %}

local_library/catalog/templates/catalog/genre_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Delete Genre: {{ genre }}</h1>

<p>Are you sure you want to delete the genre?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
</div>
{% endblock %}

local_library/catalog/templates/catalog/genre_detail.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Genre: {{ genre.name }}</h1>


<h4>Books in genre</h4>

<ul>
  {% for copy in genre.book_set.all %}
  <li>
    <a href="{{ copy.get_absolute_url }}">{{ copy.title }}</a> ({{copy.author}})
  </li>
  {% empty %}
  <li>There are no books in this genre.</li>
  {% endfor %}
</ul>
</div>
{% endblock %}


{% block sidebar %}
  {{ block.super }}

  {% if perms.catalog.change_genre or perms.catalog.delete_genre %}
  <hr>
  <!-- <ul class="sidebar-nav"> -->
    <div class="w3-sidebar w3-bar-block w3-light-grey" style="width:25%">
    {% if perms.catalog.change_genre %}
    <!-- <li> -->
      <a href="{% url 'genre-update' genre.id %}"class="w3-bar-item w3-button w3-hover-blue">Update Genre</a>
    <!-- </li> -->
    {% endif %}
    {% if not genre.book_set.all and perms.catalog.delete_genre %}
      <!-- <li> -->
        <a href="{% url 'genre-delete' genre.id %}"class="w3-bar-item w3-button w3-hover-blue">Delete Genre</a>
      <!-- </li> -->
    {% endif %}
    <!-- </ul> -->
  {% endif %}
</div>
{% endblock %}

local_library/catalog/templates/catalog/genre_form.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">

</form>
</div>
{% endblock %}

local_library/catalog/templates/catalog/genre_list.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Genre List</h1>

{% if genre_list %}
  <ul>

  {% for genre in genre_list %}
    <li>
      <a href="{{ genre.get_absolute_url }}">
      {{ genre }}
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no genres available.</p>
{% endif %}

</div>
{% endblock %}

local_library/catalog/templates/catalog/language_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Delete Language: {{ language }}</h1>

<p>Are you sure you want to delete the language?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete.">
</form>
</div>
{% endblock %}

local_library/catalog/templates/catalog/language_list.html
{% extends "base_generic.html" %}

{% block content %}
<div style="margin-left:25%">
<h1>Language List</h1>

<ul>
  {% for language in language_list %}
  <li>
    <a href="{{ language.get_absolute_url }}">{{ language }}</a>
  </li>
  {% empty %}
  <li>There are no languages available.</li>
  {% endfor %}
</ul>
</div>
{% endblock %}